# -*- coding: utf-8 -*-
"""MQTT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2yLL7G9cyTHmsOQ1lAPSInIa2UQGflj
"""

import random
import numpy as np

class RLenv:
    def __init__(self, model, num_clients=15):
        self.model = model
        self.return1 = [0 for _ in range(num_clients)]


#the state from the machine learning algorithm
    def get_state(self, nodes, episode, num_episode,routing_table,s):
      state = self.machine_learning_input()
      return state

    def machine_learning_input():
        pass

    def reward_return(self):
        for client in clients:
          reward = self.check_msg_type()
          self.return1[client] = self.return1[client]+reward

    #this function checks the msg type from the fields obtained from the dataset and takes appropriate actions according to policy
    def check_msg_type(self, msg_field, timedelta, threshold1, window_size=None):
      threshold1 = 5
      threshold2 = 8

      if msg_field == 'qos0':
          #check whether timedelta is less than the threshold
          if timedelta < threshold1:
              self.send_message_accept()
          if timedelta > threshold1:
              self.send_message_decline()

      if msg_field in ['qos1', 'connect']:
        if window_size is None:
            raise ValueError(f"Missing window_size for msg_type '{msg_field}'")

        combined = timedelta + window_size

        if combined < threshold1:
            return self.send_message_accept()
        elif threshold1 <= combined <= threshold2:
            return self.send_message_warn()
        else:
            return self.send_message_decline()

    def send_message_accept(self):
      return 1

    def send_message_decline(self):
      return 0

    def send_message_warn(self):
      return 2

    def reward_return(self, actions):
        """
        Calculate rewards for agents based on actions taken.
        """
        rewards = []
        for action in actions:
            if action == 1:
                print("Action: Accept")
                rewards.append(1)  # reward for accepting valid msg
            elif action == 2:
                print("Action: Warn")
                rewards.append(2)  # warning
            else:
                print("Action: Decline")
                rewards.append(0)  # penalty for bad behavior
        return rewards

    def machine_learning_input(self, timedelta, msg_type, window_size):
        """
        Generates ML-based classification output as state from features.
        """
        msg_type_map = {'qos0': 0, 'qos1': 1, 'connect': 2}
        msg_id = msg_type_map.get(msg_type, -1)

        # Construct input vector and predict
        features = np.array([[timedelta, msg_id, window_size]])
        prediction = self.model.predict(features)
        return int(prediction[0])  # state = 0, 1, or 2

    def run_episode(self, clients):
        actions = []
        for client in clients:
            msg_type = client['msg_type']
            td = client['timedelta']
            ws = client.get('window_size', None)

            if msg_type in ['qos1', 'connect'] and 'window_size' not in client:
                print(f"Skipping client {client['id']} due to missing window_size")
                continue
            print("Window Size:", ws)
            print("Message Type", msg_type)
            action = self.check_msg_type(msg_type, td, threshold1=5, window_size=ws)
            actions.append(action)

        rewards = self.reward_return(actions)

        for i, r in enumerate(rewards):
            self.return1[i] += r  # accumulate return for each client

class testEnv:
    def __init__(self):
        self.clients = []
        self.create_clients()

    def create_clients(self):
        msg_types = ['qos1'] * 5 + ['qos1'] * 5 + ['qos1'] * 5
        random.shuffle(msg_types)  # Shuffle to randomize client types

        for i, msg_type in enumerate(msg_types):
            client = {
                'id': i,
                'msg_type': msg_type,
                'timedelta': round(random.uniform(0, 10), 2)
            }

            if msg_type in ['qos1', 'connect']:
                client['window_size'] = 2 #random.randint(1, 10)

            print(client)

            self.clients.append(client)

# Dummy model for illustration
class DummyModel:
    def predict(self, X):
        return [0] * len(X)

# Initialize environments
model = DummyModel()
test_env = testEnv()
rl_env = RLenv(model, num_clients=len(test_env.clients))

    # Simulate multiple episodes
for episode in range(10):
   print("Episode:",episode)
   rl_env.run_episode(test_env.clients)

    # Check updated return values
for i, ret in enumerate(rl_env.return1):
   print(f"Client {i} accumulated return: {ret}")

import matplotlib.pyplot as plt
import numpy as np

# QoS1 action counts
qos1_counts = {
    2: {'accept': 6, 'decline': 1, 'warn': 3},
    4: {'accept': 5, 'decline': 2, 'warn': 3},
    6: {'accept': 3, 'decline': 3, 'warn': 4},
    8: {'accept': 1, 'decline': 5, 'warn': 4}
}

window_sizes = [2, 4, 6, 8]
labels = [str(ws) for ws in window_sizes]
accept_vals = [qos1_counts[ws]['accept'] for ws in window_sizes]
decline_vals = [qos1_counts[ws]['decline'] for ws in window_sizes]
warn_vals = [qos1_counts[ws]['warn'] for ws in window_sizes]

x = np.arange(len(window_sizes))
width = 0.25

fig, ax = plt.subplots()
ax.bar(x - width, accept_vals, width, label='Accept', color='slategrey')
ax.bar(x, warn_vals, width, label='Warn', color='thistle')
ax.bar(x + width, decline_vals, width, label='Decline', color='rebeccapurple')

# Set bold labels and title
ax.set_xlabel('Message Length', fontweight='bold',fontsize=18)
ax.set_ylabel('Number of Actions', fontweight='bold',fontsize = 18)
#ax.set_title('Action Counts for QoS1 Messages', fontweight='bold')

# Set bold xticks
ax.set_xticks(x)
ax.set_xticklabels(labels, fontweight='bold',fontsize = 14)
ax.tick_params(axis='y', labelsize=14, width=1.3)
for label in ax.get_yticklabels():
    label.set_fontweight('bold')

# Bold legend
legend = ax.legend()
for text in legend.get_texts():
    text.set_fontweight('bold')

# Remove top and right spines
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Connect action counts (replace with your actual results)
connect_counts = {
    2: {'accept': 5, 'decline': 3, 'warn': 2},
    4: {'accept': 4, 'decline': 3, 'warn': 3},
    6: {'accept': 3, 'decline': 4, 'warn': 3},
    8: {'accept': 2, 'decline': 6, 'warn': 2}
}

window_sizes = [2, 4, 6, 8]
labels = [str(ws) for ws in window_sizes]
accept_vals = [connect_counts[ws]['accept'] for ws in window_sizes]
decline_vals = [connect_counts[ws]['decline'] for ws in window_sizes]
warn_vals = [connect_counts[ws]['warn'] for ws in window_sizes]

x = np.arange(len(window_sizes))
width = 0.25

fig, ax = plt.subplots()
ax.bar(x - width, accept_vals, width, label='Accept', color='slategrey')
ax.bar(x, warn_vals, width, label='Warn', color='thistle')
ax.bar(x + width, decline_vals, width, label='Decline', color='rebeccapurple')

ax.set_xlabel('Message Length', fontweight='bold',fontsize=18)
ax.set_ylabel('Number of Actions', fontweight='bold',fontsize = 18)
#ax.set_title('Action Counts for Connect Messages')
# Set bold xticks
ax.set_xticks(x)
ax.set_xticklabels(labels, fontweight='bold',fontsize = 14)
ax.tick_params(axis='y', labelsize=14, width=1.3)
for label in ax.get_yticklabels():
    label.set_fontweight('bold')

# Bold legend
legend = ax.legend()
for text in legend.get_texts():
    text.set_fontweight('bold')

# Remove top and right spines
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Example data for qos1
qos1_data = {
    8: {'accept': 6, 'warn': 3, 'decline': 1},
    6: {'accept': 5, 'warn': 3, 'decline': 2},
    4: {'accept': 5, 'warn': 3, 'decline': 2},
    2: {'accept': 1, 'warn': 1, 'decline': 8}
}

bins = sorted(qos1_data.keys())
labels = [str(b) for b in bins]
accept_vals = [qos1_data[b]['accept'] for b in bins]
warn_vals = [qos1_data[b]['warn'] for b in bins]
decline_vals = [qos1_data[b]['decline'] for b in bins]

x = np.arange(len(bins))
width = 0.25

fig, ax = plt.subplots()
ax.bar(x - width, accept_vals, width, label='Accept', color='slategrey')
ax.bar(x, warn_vals, width, label='Warn', color='thistle')
ax.bar(x + width, decline_vals, width, label='Decline', color='rebeccapurple')

ax.set_xlabel('Time Delta', fontweight='bold',fontsize=18)
ax.set_ylabel('Number of Actions', fontweight='bold',fontsize=18)
#ax.set_title('QoS1 Messages: Actions vs Timedelta')
ax.set_xticks(x)
ax.set_xticklabels(labels, fontweight='bold',fontsize=14)
ax.tick_params(axis='y', labelsize=14, width=1.3)
for label in ax.get_yticklabels():
    label.set_fontweight('bold')

# Bold legend
legend = ax.legend()
for text in legend.get_texts():
    text.set_fontweight('bold')

ax.spines['top'].set_visible(True)
ax.spines['right'].set_visible(True)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Example data for qos1
qos1_data = {
    8: {'accept': 6, 'warn': 3, 'decline': 1},
    6: {'accept': 5, 'warn': 4, 'decline': 1},
    4: {'accept': 4, 'warn': 3, 'decline': 3},
    2: {'accept': 1, 'warn': 2, 'decline': 7}
}

bins = sorted(qos1_data.keys())
labels = [str(b) for b in bins]
accept_vals = [qos1_data[b]['accept'] for b in bins]
warn_vals = [qos1_data[b]['warn'] for b in bins]
decline_vals = [qos1_data[b]['decline'] for b in bins]

x = np.arange(len(bins))
width = 0.25

fig, ax = plt.subplots()
ax.bar(x - width, accept_vals, width, label='Accept', color='slategrey')
ax.bar(x, warn_vals, width, label='Warn', color='thistle')
ax.bar(x + width, decline_vals, width, label='Decline', color='rebeccapurple')

ax.set_xlabel('Time Delta', fontweight='bold',fontsize=18)
ax.set_ylabel('Number of Actions', fontweight='bold',fontsize=18)
#ax.set_title('QoS1 Messages: Actions vs Timedelta')
ax.set_xticks(x)
ax.set_xticklabels(labels, fontweight='bold',fontsize=14)
ax.tick_params(axis='y', labelsize=14, width=1.3)
for label in ax.get_yticklabels():
    label.set_fontweight('bold')

# Bold legend
legend = ax.legend()
for text in legend.get_texts():
    text.set_fontweight('bold')

ax.spines['top'].set_visible(True)
ax.spines['right'].set_visible(True)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Example timedelta bins and corresponding action counts for qos0
qos0_data = {
    8: {'accept': 8, 'decline': 2},
    6: {'accept': 7, 'decline': 3},
    4: {'accept': 5, 'decline': 5},
    2: {'accept': 3, 'decline': 7}
}

# Sort bins and extract data
bins = sorted(qos0_data.keys())
labels = [str(b) for b in bins]
accept_vals = [qos0_data[b]['accept'] for b in bins]
decline_vals = [qos0_data[b]['decline'] for b in bins]

x = np.arange(len(bins))
width = 0.35  # Adjusted width for better side-by-side appearance

# Plotting
fig, ax = plt.subplots()
ax.bar(x - width/2, accept_vals, width, label='Accept', color='slategrey')
ax.bar(x + width/2, decline_vals, width, label='Decline', color='rebeccapurple')

# Labeling
ax.set_xlabel('Time Delta', fontweight='bold', fontsize=18)
ax.set_ylabel('Number of Actions', fontweight='bold', fontsize=18)
ax.set_xticks(x)
ax.set_xticklabels(labels, fontweight='bold', fontsize=14)
ax.tick_params(axis='y', labelsize=14)
for label in ax.get_yticklabels():
    label.set_fontweight('bold')

# Legend
legend = ax.legend()
for text in legend.get_texts():
    text.set_fontweight('bold')

# Aesthetics
ax.spines['top'].set_visible(True)
ax.spines['right'].set_visible(True)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Sample data for demonstration
returns_70 = [10, 12, 14, 15, 13, 14, 16]
returns_80 = [18, 19, 20, 21, 19, 20, 22]
returns_90 = [22, 23, 22, 24, 25, 24, 23]

data = [returns_70, returns_80, returns_90]
labels = ['70% Non-Attack', '80% Non-Attack', '90% Non-Attack']

plt.figure(figsize=(10, 6))
box = plt.boxplot(data, patch_artist=True, labels=labels)

# Style the box plot
colors = ['lightblue', 'lightgreen', 'lightyellow']
for patch, color in zip(box['boxes'], colors):
    patch.set_facecolor(color)

# Set bold and large font sizes
#plt.title('Agent Return Distribution Across Traffic Types', fontsize=18, fontweight='bold')
plt.xlabel('Traffic Type', fontsize=18, fontweight='bold')
plt.ylabel('Return', fontsize=18, fontweight='bold')

# Make tick labels bold and size 18
plt.xticks(fontsize=14, fontweight='bold')
plt.yticks(fontsize=14, fontweight='bold')

# Remove grid lines
plt.grid(False)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generate x-axis values
iterations = np.arange(0, 100, 25)
n = len(iterations)

# Simulate curves with small random fluctuations
epsilon_0_0 = np.linspace(85, 97, n) + np.random.normal(0, 0.5, n)
epsilon_0_1 = np.linspace(75, 93, n) + np.random.normal(0, 0.5, n)
epsilon_0_15 = np.linspace(75, 91, n) + np.random.normal(0, 0.5, n)
epsilon_0_2 = np.linspace(74, 89, n) + np.random.normal(0, 0.5, n)

plt.figure(figsize=(10, 6))

# Plot dashed lines
plt.plot(iterations, epsilon_0_0, 'b--', linewidth=2.5, label='ε = 0.0')
plt.plot(iterations, epsilon_0_1, color='orange', linestyle='--', linewidth=2.5, label='ε = 0.1')
plt.plot(iterations, epsilon_0_15, color='brown', linestyle='--', linewidth=2.5, label='ε = 0.15')
plt.plot(iterations, epsilon_0_2, color='cyan', linestyle='--', linewidth=2.5, label='ε = 0.2')

# Axis labels
plt.xlabel('Epochs', fontsize=16, fontweight='bold')
plt.ylabel('% of Optimal State-Action', fontsize=16, fontweight='bold')

# Set y-axis starting at 0
plt.ylim(0, 100)

# Bold ticks
plt.xticks(fontsize=12, fontweight='bold')
plt.yticks(fontsize=12, fontweight='bold')

# Bold and prominent legend
legend = plt.legend(loc='lower right', fontsize=14, frameon=True, facecolor='white', edgecolor='black')
for text in legend.get_texts():
    text.set_fontweight('bold')

# Layout
plt.tight_layout()
plt.show()